execute_process(
  COMMAND git log -1 --format=%H
  WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
  OUTPUT_VARIABLE GIT_COMMIT_HASH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
  COMMAND git log -1 --format=%cD
  WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}
  OUTPUT_VARIABLE GIT_COMMIT_DATE
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

set(LIBPARAKEET_GIT_COMMIT_HASH "${GIT_COMMIT_HASH}" CACHE INTERNAL "")
set(LIBPARAKEET_GIT_COMMIT_DATE "${GIT_COMMIT_DATE}" CACHE INTERNAL "")
