name: Coverage (Linux x86_64)

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  schedule:
    # Build once every fortnight
    - cron: "10 4 1,15 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  coverage:
    name: "Test & coverage"

    runs-on: ubuntu-22.04
    env:
      CC: gcc-11

    steps:
      - name: "⏳ Clone repo..."
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "🖼️ Setup scene..."
        shell: bash
        run: |
          mkdir -p build
          sudo apt-get update
          sudo apt-get install ninja-build lcov

      - name: "🔧 CMake: Configure"
        shell: bash
        working-directory: build
        run: |
          cmake \
            -D"CMAKE_BUILD_TYPE"="Debug" \
            -G Ninja \
            -DCMAKE_CXX_FLAGS_DEBUG="-g -fprofile-arcs -ftest-coverage" \
            -DCMAKE_C_FLAGS_DEBUG="-g -fprofile-arcs -ftest-coverage" \
            ..

      - name: "🛠️ CMake: Build"
        working-directory: build
        run: cmake --build .

      - name: "💣 CTest: Unit Test"
        working-directory: build
        run: |
          ctest -T Test -T Coverage --output-on-failure
          lcov --base-directory . --directory . -c \
            --exclude '/usr*' \
            --exclude '*msys*' \
            --exclude "*.test.cxx" \
            --exclude "*googlemock*" \
            --exclude "*googletest*" \
            -o libtc_tea.info
          genhtml -o ./coverage -t "libtc_tea test coverage" --num-spaces 4 libtc_tea.info

      - name: "Upload Coverage to Coveralls"
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./build/libtc_tea.info"
          flag-name: "Unit Test"

      - name: "Upload Coverage data to artifact"
        uses: actions/upload-artifact@v3
        with:
          name: libparakeet-audio-amd64.coverage
          path: |
            build/libtc_tea.info
            build/coverage
